title: My blog of despair
author: Ksenia Korolkevitch
email: kkoro1@ocdsb.com
description: > # this means to ignore newlines until "baseurl:"
  Come read this if you are interested in cats and other troublesome (but not really) things in my life
theme: minima

# social links
github_username:  Kkoro1

show_excerpts: true # set to false to remove excerpts on the homepage
